// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive.dart';
import 'package:mood_tracker/mood_tracker/data/data.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(MoodAdapter());
    registerAdapter(MoodEntryAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(MoodAdapter());
    registerAdapter(MoodEntryAdapter());
  }
}
